# Generated by Django 6.0.4 on 2026-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
